server:
  port: "${PORT:5000}"
spring:
  application:
    name: killerpartyback
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true