name: CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'

      - name: Install dependencies
        run: npm install ./frontend/killer-party-front

      - name: Build Angular app
        run: npm run build --prefix ./frontend/killer-party-front

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew build
          ls -l build/libs
          ls -l build/resources/main/static

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: killerparty-backend-jar
          path: build/libs/killerpartyback-0.0.1-SNAPSHOT.jar

      - name: Install Flyway
        run: wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/11.3.4/flyway-commandline-11.3.4-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-11.3.4/flyway /usr/local/bin

      - name: Run Flyway migrate
        env:
          FLYWAY_URL: ${{ secrets.DB_URL }}
          FLYWAY_USER: ${{ secrets.DB_USER }}
          FLYWAY_PASSWORD: ${{ secrets.DB_PASSWORD }}
          FLYWAY_DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          flyway info -locations=filesystem:./src/main/resources/db/migration/
          flyway migrate -locations=filesystem:./src/main/resources/db/migration/
